http:
  routers:

    admin-traefik:
      rule: "PathPrefix(`/admin/traefik`)"
      service: api@internal
      middlewares:
        - redirect2dashboard

    traefik-dashboard:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      middlewares:
        - admin-auth

  middlewares:
    redirect2dashboard:
      redirectRegex:
        regex: '^(http|https)\:\/\/(\[[\w:.]+\]|[\w\._-]+)/admin/traefik(|\/(.*))$'
        replacement: "${1}://${2}/dashboard/"
        permanent: true


