#!/bin/bash

source /services/helpers/run_as.sh

# Copy the nextcloud config to nextcloud config
for f in `ls -1 /tmp/config/nextcloud/*.php`; do
  cat $f | sed -e 's/{{LOCAL_DOMAIN_NAME}}/${LOCAL_DOMAIN_NAME}/g' > /var/www/html/config/`basename $f`;
done
chown -R ${RUN_AS_USER}:root /var/www/html/config/

# Copy the php config to php part.
cp -rf /tmp/config/php/*.ini /usr/local/etc/php/conf.d/

# This nextcloud-app is run from apache2
apache2-foreground
