http:
  middlewares:

    LAN-auth:
      chain:
        middlewares:
          - admin-auth
          - known-ips

    admin-auth:
      basicAuth:
        users:
          - "admin:$apr1$5draFjdn$m0uImDzEpopi5y3FMwfvl/"

    known-ips:
      ipWhiteList:
        sourceRange:
          - "192.168.1.0/24"
          - "127.0.0.1/32"
