version: "3.5"

services:
  dnsmasq:
    image: andyshinn/dnsmasq
    restart: always
    depends_on:
      - dnsmasq-config
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ${TMP_FOLDER}/dnsmasq/config:/etc/dnsmasq.d
      - ${PWD}/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ${PWD}/dnsmasq/dnsmasq-start.sh:/dnsmasq-start.sh:ro
    networks:
      - front-end
    entrypoint: sh /dnsmasq-start.sh

  dnsmasq-config:
    image: zcchen/toolbox
    restart: always
    volumes:
      - ${TMP_FOLDER}/dnsmasq/config:/mnt
      - ${PWD}/dnsmasq/setup/scripts.d:/scripts.d:ro
      - ${PWD}/dnsmasq/setup/command.sh:/command.sh:ro
    environment:
      WORK_DIR: /mnt
      SHELL_DIR: /scripts.d/
      #UPDATE_INTERVAL: 60
      SERVER_IP_ADDR:
      LOCAL_DOMAIN_NAME:
      SERVER_DOMAIN_NAME:
    network_mode: none
    command:
      [ "bash", "/command.sh" ]
