#!/usr/bin/env sh

while [ -z "`which rclone`" ]; do
    echo "[ERROR] rclone not found, wait 10s and try agian..."
    sleep 10
done

sed -i /config/rclone.conf \
  -e "s/{{NEXTCLOUD_PUBLIC_PASSWORD}}/`cat /run/secrets/nextcloud-public-password | rclone obscure -`/g";

