################################################################
#
# Configuration sample for Traefik v2.
#
# For Traefik v1: https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
#
################################################################

################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true

################################################################
# EntryPoints configuration
################################################################
entryPoints:
  http:
    address: :80
  https:
    address: :443
  #mysql:
    #address: :3306

################################################################
# API and dashboard configuration
################################################################

api:
  # Enable the API in insecure mode (Optional)
  # Default: false
  insecure: true

  # Enabled Dashboard (Optional)
  # Default: true
  dashboard: true

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
log:
  # Log level (Optional)
  # Default: "ERROR"
  level: ERROR

  # Sets the filepath for the traefik log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary. (Optional)
  # Default: os.Stdout
  filePath: os.Stdout

  # Format is either "json" or "common". (Optional)
  # Default: "common"
  format: common

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields. (Optional)
accessLog:
  # Sets the file path for the access log. If not specified, stdout will be used.
  # Intermediate directories are created if necessary. (Optional
  # Default: os.Stdout
  filePath: os.Stdout

  # Format is either "json" or "common". (Optional)
  # Default: "common"
  format: common

################################################################
# Ping configuration
################################################################

# Enable ping
#ping:
  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
#  entryPoint: traefik

################################################################
# Docker configuration backend
################################################################

providers:
  # Enable Docker configuration backend
  docker:
    # Docker server endpoint. Can be a tcp or a unix socket endpoint. (Required)
    # Default: "unix:///var/run/docker.sock"
    endpoint: unix:///var/run/docker.sock

    # Default host rule. (Optional)
    # Default: "Host(`{{ normalize .Name }}`)"
    defaultRule: "Host(`localhost`) && Path(`/{{ normalize .Name }}`)"

    # Expose containers by default in traefik (Optional)
    # Default: true
    exposedByDefault: false

    watch: true
    #network: mid_layout
