# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 2
    libvirt.nested = true
    libvirt.memory = 2048
  end

  config.vm.box = "debian/buster64"
  config.vm.synced_folder "../", "/vagrant", nfs_version: "3"

  config.vm.define "nas-server" do |nas|
    nas.vm.network :private_network, ip: "192.168.100.100"
  end

  config.vm.define "nas-local" do |nas|
    nas.vm.network :private_network, ip: "192.168.100.101"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y docker.io make python3-pip
    apt clean -y
    pip3 --no-cache-dir install docker-compose
    sudo usermod --append --groups docker vagrant
    export PATH="/home/vagrant/.local/bin:$PATH"

    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
    sed -i -e 's/# zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' /etc/locale.gen
    echo 'LANG="en_US.UTF-8"' > /etc/default/locale
    dpkg-reconfigure --frontend=noninteractive locales
    update-locale LANG=en_US.UTF-8

    if [[ -z `cat /etc/resolv.conf | grep '127.0.0.1'` ]]; then
      sed -i '1 i\ nameserver 127.0.0.1' /etc/resolv.conf
    fi
  SHELL

end
