version: "3.5"

services:
  frpc:
    image: zcchen/frpc
    restart: unless-stopped
    secrets:
      - frpc-token
    network_mode: host
    volumes:
      - ./configs/:/configs:ro
    environment:
      AUTH_TOKEN_FILE: /run/secrets/frpc-token
      SERVER_ADDR: ${SERVER_DOMAIN_NAME}
      SERVER_PORT: 7000
      APPEND_CONFIG_FILES:
        /configs/ssh.ini
      SHOW_CONFIG: "false"    # change it to true for easy debug if needed

secrets:
  frpc-token:
    file: ../configs/secrets/frp/token.txt
