version: "3.5"

services:

  mysql-db-test-root:
    image: mariadb
    container_name: mysql-db-test-root
    restart: on-failure
    secrets:
      - mysql_root_password
    networks:
      - back_end
    depends_on:
      - mysql-db
    command: /bin/bash -c "mysql -v -uroot -p`cat /run/secrets/mysql_root_password` --protocol=tcp --host=mysql-db --execute='show databases;'"

  mysql-db-test-admin:
    image: mariadb
    container_name: mysql-db-test-admin
    restart: always
    secrets:
      - mysql_admin_password
    networks:
      - back_end
    depends_on:
      - mysql-db
    command: /bin/bash -c "mysql -v -uadmin -p`cat /run/secrets/mysql_admin_password` --protocol=tcp --host=mysql-db --execute='show databases;'"

